### ISSUE TITLE
PHP 8 Container

### ISSUE THREAD

**Issue by luisdalmolin** [kirschbaum-development/laravel-test-runner-container#10]
Add a container for PHP 8.

**Comment by pushpak1300** [comment]
Hey, @luisdalmolin I'm interested to contribute to this issue.
I just wanted to know which php image I should use?

**Comment by luisdalmolin** [comment]
Hey @pushpak1300, that's awesome - No real preference here, if you can make it work with the `ondrej/php` repository is better, otherwise whatever you can make it work. I didn't dig into to see if PHP 8 beta is already published in this repository.

**Comment by pushpak1300** [comment]
I think https://github.com/oerdnj/deb.sury.org/issues/1439 ondrej/php will take time so I will build it from source for now!
