### ISSUE TITLE
Restart Mysql after config changes 

### ISSUE THREAD

**Issue by madsem** [kirschbaum-development/laravel-test-runner-container#11]
Hi,

thanks for this!

How can I customize mysql config? 
My Laravel project requires LOAD DATA LOCAL INFILE...

 I'm mounting a local volume to the latest mysql docker image, to set secure-file-priv and load_infile options.

I would then need to restart mysql in my Github action, but no sudo etc. command is found...

If that has nothing to do with how the runner is configured I apologize ;)

**Comment by luisdalmolin** [comment]
@madsem Yeah, this doesn't have a relation with this container here, but if you want to post the code here, I can try to help.

**Comment by madsem** [comment]
@luisdalmolin thanks, I appreciate that a lot :)
I don't have the code anymore, I ended up using the default Ubuntu 20.04 container that GitHub provides.
Then I just edit the settings and start the Mysql service.

The issue was this here though: https://github.community/t/setting-secure-file-priv-not-affects-mysql/18280/6

I used your runner, and then a mysql 8 docker image, but could not restart the service as commands like `sudo` etc were not found.

Similar yaml config:
```
services:
      mysql:
        image: mysql:5.7.24
# Setup a volume so you can inject your custom config
        volumes:
          - /my/custom:/etc/mysql/conf.d
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
# Give the instance a name to access it easier below
        options:
--name=my-docker-mysql
--health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
steps:
- name: Tweak mysql settings and restart, getting the new port number
run: |
echo -e "[mysqld]\nsecure-file-priv=''" | sudo tee -a /my/custom/my.cnf
docker restart my-docker-mysql
sleep 20 # Let it restart and get healthy
MY_CUSTOM_MYSQL_PORT=$(docker inspect --format='{{(index (index .NetworkSettings.Ports "3306/tcp") 0).HostPort}}' my-docker-mysql)
mysql --host 127.0.0.1 --port $MY_CUSTOM_MYSQL_PORT -uroot -ppassword -e "SELECT @@global.secure_file_priv"
```

I'll go ahead and close this issue, but maybe it helps others.

Thanks again for your help, hope you're gonna a great day! ;)

**Comment by luisdalmolin** [comment]
Hmm yeah, not really sure, would have to debug to see. But maybe what you could do is create a custom docker image with these configurations, publish, and then use your image instead of `image: mysql:5.7.24`. Then you won't have to restart/sleep to wait for the restart.

Hope you have a great day as well!
