### ISSUE TITLE
How to run NPM CI in a git worklow

### ISSUE THREAD

**Issue by tcampbPPU** [kirschbaum-development/laravel-test-runner-container#14]
In my workflow file I'd like to run `npm ci` to utilize my package-lock for a faster install.
When I try to do currently:
`npm ci --prefix client`
it fails and does not recognize the command.

I am using 

image: `kirschbaumdevelopment/laravel-test-runner:7.3`
on: `ubuntu-latest`

Is there something I am missing to get this working?

Thanks :)

**Comment by luisdalmolin** [comment]
This is likely due to the NodeJS version the package install. I've never heard of `npm ci` until now, but I think we can upgrade the NodeJS version of the containers.

**Comment by luisdalmolin** [comment]
@tcampbPPU A new version was just published, can you try again?

**Comment by tcampbPPU** [comment]
Great! Upgrading the NodeJS version fixed it for me. Thanks for the help 😃
