### ISSUE TITLE
Can you update Composer version in the the PHP 8 test runner?

### ISSUE THREAD

**Issue by tcampbPPU** [kirschbaum-development/laravel-test-runner-container#16]
Hi, I am running into a few issue with my CI pipeline due to the composer version in use. Do you think you could update to composer version 2?
![image](https://user-images.githubusercontent.com/25044744/109332123-b1fce580-782b-11eb-8f33-995ed8dfa532.png)

**Comment by luisdalmolin** [comment]
Done, and I have also updated the PHP version to 8.0.2. You cah check in the tags `8.0` and `8.0.2`.

**Comment by tcampbPPU** [comment]
I appreciate it!
