### ISSUE TITLE
Composer update needed to fix error from new GitHub token format

### ISSUE THREAD

**Issue by aharp-afg** [kirschbaum-development/laravel-test-runner-container#19]
I'm using this image to run tests for a Laravel project using a GitHub action. It appears GitHub has changed the format of their token which is causing an `[UnexpectedValueException]` error when calling `composer config -g github-oauth.github.com *TOKEN*`. The issue is described [here](https://github.com/composer/composer/issues/8314) and is fixed in the latest version of Composer. Can you update the images to use Composer 2.0.12?

**Comment by luisdalmolin** [comment]
@aharp-afg Done, pushed new images for 7.3, 7.4 and 8.0.

**Comment by aharp-afg** [comment]
@luisdalmolin Thank you!

**Comment by aharp-afg** [comment]
I'm still getting the same error. Is there a certain way you have to tell GitHub to pull the latest version of the image?

**Comment by luisdalmolin** [comment]
I'm not sure tbh, you may be able to clear the GH cache for actions.
