### ISSUE TITLE
phpunit very slow?

### ISSUE THREAD

**Issue by danielzzz** [kirschbaum-development/laravel-test-runner-container#24]
hi, thanks for this image.

I have been trying to use it with my laravel build, but it seems that phpunit is very slow here.
not sure if it's my server but it times out after 5 mins.
the same tests need <10 seconds on my local machine

my doubt is, does it use in memory sqlite db? 
I have seen it doesn't have pdo_sqlite in modules...

thanks, cheers, dan

**Comment by danielzzz** [comment]
sorry, just realized you're installing 
    php7.4-sqlite3 \

**Comment by luisdalmolin** [comment]
This seems like a configuration issue where it's not being able to connect to the right place. Sorry to answer this 6 months after, though 😓
